### ISSUE TITLE
CourtBot does not forget conversation history

### ISSUE THREAD

**Issue by agboise** [boisebrigade/courtbot#28]
User had conversation with CourtBot on 3/18, almost a month later tried to start a new conversation and CourtBot continued old conversation. 
Example:
3/18/19: User input case number, received :county prompt, responded with county, received :subscribe prompt, did not reply. 
4/16/19: User input different case number, received :yes_or_no prompt (see screenshots)

We expect that CourtBot will forget current conversation after a short period of time.
![1](https://user-images.githubusercontent.com/45367593/56241135-50c23380-6052-11e9-897c-98bf9dbd2613.png)
![2](https://user-images.githubusercontent.com/45367593/56241139-53bd2400-6052-11e9-8595-c6beeb9e013a.png)

**Comment by tylersamples** [comment]
I adjusted the cookie time to 4hr to match Twilio in 0.3.0-beta3
