### ISSUE TITLE
need :resubscribe if not unsubscribed

### ISSUE THREAD

**Issue by agboise** [boisebrigade/courtbot#30]
User inputs "Start" without ever inputting "Stop", CourtBot replies with :resubscribe ("You are not currently subscribed to any cases") even though user is currently subscribed to a case. This is working as expected, but we need to review this logic and either come up with a revised message or a second flow for this use case.

![image](https://user-images.githubusercontent.com/45367593/56244135-6b4bdb00-6059-11e9-9f7c-707e71f5b318.png)

**Comment by agboise** [comment]
I also just realized I have two copies with two different :resubscribe messages. This one (in screenshot) and "You will need to resubscribe to the case to receive hearing reminders". So just in case it comes up, the current configuration is the correct message. I'll try to pull that old message out of any current documentation.

**Comment by tylersamples** [comment]
Made some adjustments to the copy for 0.3.0-beta3 to not show the user "You are not subscribed to any cases" if they are infact subscribed to cases.
